version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=zerodha_clone
    restart: always

  # Redis Service
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/zerodha_clone
      - JWT_SECRET=your_jwt_secret_key_here
      - REDIS_URL=redis://redis:6379
      - FINNHUB_API_KEY=your_finnhub_api_key
    depends_on:
      - mongodb
      - redis
    restart: always

  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    restart: always

# Volumes for persistent data
volumes:
  mongodb_data:
  redis_data:
